title: M3ll0wN1ght
logo: /assets/img/Lain_Iwakura.png
email: arabidopsis10@gmail.com
description: |
              Programmer, reverse engineer, and novice security researcher.
              
              Learning since October 2018  
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/MellowNight
  - name: Blog
    icon: <i class="fa-solid fa-pen"></i>
    link: https://mellownight.github.io/posts.html
  - name: Linkedin
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com
  - name: "MellowNight#9746"
    icon: <i class="fa-brands fa-discord"></i>

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
